version: '3.4'

services:
  Aquila.tests:
    image: ${DOCKER_REGISTRY}Aquilatests
    build:
      context: .
      dockerfile: Aquila.Tests/Dockerfile
  db:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
# Volumes
volumes:
  db_data: