using System.Collections.Concurrent;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading;
using Aquila.CodeAnalysis.Symbols;
using Aquila.CodeAnalysis.Symbols.Synthesized;
using Microsoft.CodeAnalysis;

namespace Aquila.CodeAnalysis.Public
{
    public interface ITypeResolver
    {
        public IType FindType(string namespaceName, string typeName);
    }

    public interface INamespace
    {
        public IType FindType(string name);
    }

    public interface INamespaceBuilder
    {
        public IType DefineType(string name);
    }

    public interface IType
    {
    }

    public interface ITypeBuilder : IType
    {
        public IMethodBuilder CreateMethod();
    }

    public interface IMember
    {
    }

    public interface IMethod : IMember
    {
    }

    public interface IMethodBuilder : IMethod
    {
    }

    public interface IField : IMember
    {
    }

    public interface IProperty : IMember
    {
    }

    //Manage types generated by components
    public class ComponentTypeManager
    {
        internal ComponentTypeManager(AquilaCompilation compilation)
        {
            Debug.Assert(compilation != null);
            this.Compilation = compilation;
        }

        /// <summary> 
        /// Current compilation.
        /// </summary>
        public AquilaCompilation Compilation { get; }

        #region Types

        private ConcurrentBag<NamedTypeSymbol> _lazySynthesizedTypes;

        public ITypeBuilder SynthesizeType()
        {
            var type = new SynthesizedTypeSymbol(Compilation);

            if (_lazySynthesizedTypes == null)
            {
                Interlocked.CompareExchange(ref _lazySynthesizedTypes, new ConcurrentBag<NamedTypeSymbol>(), null);
            }

            _lazySynthesizedTypes.Add(type);

            return type;
        }

        #endregion

        #region Symbols

        public IType System_Object
        {
            get { return Compilation.GetSpecialType(SpecialType.System_Object); }
        }

        public IType System_Void
        {
            get { return Compilation.GetSpecialType(SpecialType.System_Void); }
        }

        public IType System_Boolean
        {
            get { return Compilation.GetSpecialType(SpecialType.System_Boolean); }
        }

        public IType System_String
        {
            get { return Compilation.GetSpecialType(SpecialType.System_String); }
        }

        public IType System_Int32
        {
            get { return Compilation.GetSpecialType(SpecialType.System_Int32); }
        }

        public IType System_Diagnostics_DebuggerBrowsableState
        {
            get { return Compilation.GetWellKnownType(WellKnownType.System_Diagnostics_DebuggerBrowsableState); }
        }

        public IMethod System_Object__Equals
        {
            get { return this.Compilation.GetSpecialTypeMember(SpecialMember.System_Object__Equals) as MethodSymbol; }
        }

        public IMethod System_Object__ToString
        {
            get { return this.Compilation.GetSpecialTypeMember(SpecialMember.System_Object__ToString) as MethodSymbol; }
        }

        public IMethod System_Object__GetHashCode
        {
            get
            {
                return this.Compilation.GetSpecialTypeMember(SpecialMember.System_Object__GetHashCode) as MethodSymbol;
            }
        }

        public IMethod System_Runtime_CompilerServices_CompilerGeneratedAttribute__ctor
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Runtime_CompilerServices_CompilerGeneratedAttribute__ctor) as MethodSymbol;
            }
        }

        public IMethod System_Diagnostics_DebuggerHiddenAttribute__ctor
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Diagnostics_DebuggerHiddenAttribute__ctor) as MethodSymbol;
            }
        }

        public IMethod System_Diagnostics_DebuggerBrowsableAttribute__ctor
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Diagnostics_DebuggerBrowsableAttribute__ctor) as MethodSymbol;
            }
        }

        public IMethod System_Collections_Generic_EqualityComparer_T__Equals
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Collections_Generic_EqualityComparer_T__Equals) as MethodSymbol;
            }
        }

        public IMethod System_Collections_Generic_EqualityComparer_T__GetHashCode
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Collections_Generic_EqualityComparer_T__GetHashCode) as MethodSymbol;
            }
        }

        public IMethod System_Collections_Generic_EqualityComparer_T__get_Default
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember
                    .System_Collections_Generic_EqualityComparer_T__get_Default) as MethodSymbol;
            }
        }

        public IMethod System_String__Format_IFormatProvider
        {
            get
            {
                return this.Compilation.GetWellKnownTypeMember(WellKnownMember.System_String__Format_IFormatProvider) as
                    MethodSymbol;
            }
        }

        #endregion
    }

    public interface IAnalysesComponent
    {
        AquilaCompilation PopulateAssemblyReference(AquilaCompilation compilation);
        AquilaCompilation PopulateTypes(AquilaCompilation compilation);
        AquilaCompilation PopulateMembers(AquilaCompilation compilation);
    }
}