namespace ZenPlatform.UIGeneration2 {
    public enum ControlType {

        SilverlightButton,
        SilverlightCheckBox,
        SilverlightComboBox,
        SilverlightDatePicker,
        SilverlightImage,
        SilverlightTextBlock,
        SilverlightTextBox,
        SilverlightSlider,
        UwpButton,
        UwpCheckBox,
        UwpComboBox,
        UwpDatePicker,
        UwpImage,
        UwpTextBlock,
        UwpTextBox,
        UwpToggleButton,
        UwpSlider,
        WpfButton,
        WpfCheckBox,
        WpfComboBox,
        WpfDatePicker,
        WpfImage,
        WpfLabel,
        WpfTextBlock,
        WpfTextBox,
        WpfSlider,
        XamarinBindablePicker,
        XamarinButton,
        XamarinDatePicker,
        XamarinEditor,
        XamarinEntry,
        XamarinImage,
        XamarinLabel,
        XamarinPicker,
        XamarinSlider,
        XamarinStepper,
        XamarinSwitch,
        XamarinTimePicker

    }
}
